### ISSUE TITLE
When using Shuffle BN, loss goes to nan and accuracy goes to 100%

### ISSUE THREAD

**Issue by Hhhhhhao** [TengdaHan/ShuffleBN#2]
I'm trying to use this shuffle BN implementation, but once I convert to shuffle BN and train my model.
My loss goes to nan and accuracy goes to 100
Did you encountered similar problems? Where could be the potential bug?

**Comment by Hhhhhhao** [comment]
After detailed check with values, I find that if using shuffle BN with a deep model. The input to BN will go to inf, thus producing nan mean and nan std. 

Actually I find that implementing shuffle BN in this way might be meaningless. If we change BN statistics across card, then the output of BN wouldn't be a distribution that have mean of 0 and std of 1. This breaks the meaning of implementing BN and introduce exploding numerical values.

**Comment by TengdaHan** [comment]
Yes, I found the same problem but haven't found a way to fix the nan issue. I guess editing the BN computation brings some stability issue. If you have any suggestions, please let me know, thanks!
I agree, switching across GPU is a way to shuffle BN. But this repo was planned to implement a single-GPU solution.
