### ISSUE TITLE
Can ShuffleBN be used in one-gpu computer?

### ISSUE THREAD

**Issue by NeuZhangQiang** [TengdaHan/ShuffleBN#3]
Does it means that I can not run the MOCO if I have only one-gpu?

**Comment by TengdaHan** [comment]
You can, but you need to mimic the situation of multi-gpu. You can have 2 copies of BN layers and split your batch samples into 2 parts, then swap BN statistics to use BN. 
e.g. rewrite these functions to run on a single gpu: https://github.com/facebookresearch/moco/blob/78b69cafae80bc74cd1a89ac3fb365dc20d157d3/moco/builder.py#L69

**Comment by NeuZhangQiang** [comment]
If I replace the batch normalization with layer normalization, can I remove the shuffleBN from MOCO?

**Comment by TengdaHan** [comment]
Yes conceptually you can, but the performance is not guaranteed.

**Comment by NeuZhangQiang** [comment]
Thank you very much for your kindly reply, and I still have one question. The original paper said: the Shuffling BN is used to prevent information leakage. Why the BN would cause the information leakage?

In the question ["Different understanding of `Shuffling BN`"](https://github.com/TengdaHan/ShuffleBN/issues/1), you said: "when the model learns its feature, it should not 'see' other samples in the same batch".  I don't understand this sentence. 

My understanding of information leakage is:
If there is four gpu and the batch size is 32, the gpu1 has 0~7 samples, gpu2 has 8-15 samples, gpu3 has 16-23 samples, and gpu4 has 24-31 samples. The key encoder is f_k, and query encoder is f_q. Thus, the f_q is included in gpu1. Is it correct? For BN, the gpu1 would collect the information of f_q, but gpu2/3/4 do not see the information of f_q. Thus, it cause the information leakage. For Shuffling BN, the f_q may be randomly contained in gpu1/2/3/4, and it do not know which sample is f_q. Is my understanding correct?

If the above understanding is correct, I think the information leakage can be prevent if there is only one GPU. 

Please correct me if my understanding is wrong.
